### ISSUE TITLE
Units

### ISSUE THREAD

**Issue by anthonykgross** [foxdb/thetpgame-issue-tracker#1]
Wrong unit for thousands 

...
$998
$999
$1000k
...

$1000 != $1000k

**Comment by foxdb** [comment]
I can't reproduce this @anthonykgross , do you have a screenshot handy? Here are mine (one before passing the 1k limit, one after)
![Screenshot_20200404-174314_Chrome](https://user-images.githubusercontent.com/1695374/78420581-0e976500-769c-11ea-93d9-0c5ecd3fe53a.jpg)
![Screenshot_20200404-174323_Chrome](https://user-images.githubusercontent.com/1695374/78420582-10f9bf00-769c-11ea-9da5-b584e5de1672.jpg)

**Comment by anthonykgross** [comment]
Yes but you reproduced it. I think it's my bad. It's not $1000k but $1.000k

It's a bit ambiguous because $1.000k very similar to $1,000k

Anyway, that wasn't an issue. 

My bad, mate !

**Comment by anthonykgross** [comment]
was't*
